### ISSUE TITLE
On new install, using demo site, yst fails on april_events.tex

### ISSUE THREAD

**Issue by DrEntropy** [jgm/yst#38]
I am just starting with YST, using windows 8 (ugh i know. Because, reasons.)  Anyway, I did a fresh cabal install yst, dealt with the issue of sqllite3 not being on my system, and finally got it to run.

yst create mysite: This executed fine
cd mysite
yst 

The last command failed with
yst: site\april_events.tex: commitBuffer: invalid argument (invalid character)

Looking at april_events.tex, the file looks incomplete, last line is "Jim Jones, \emph{"

(PS I think it might have something to do with the unicode in that file, and in index.st)

**Comment by aerphanas** [comment]
i don't know about windows but, yst works great on NixOS 22.11

here what april_events.tex, look like
```latex
\documentclass{article}
\usepackage{amsmath}
\usepackage[mathletters]{ucs}
\usepackage[utf8x]{inputenc}
\usepackage{hyperref}
\usepackage{listings}

\lstnewenvironment{code}{\lstset{language=Haskell,basicstyle=\small\ttfamily}}{}

\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}

\title{April Events}

\begin{document}
\maketitle

Here's what happened in April:

\begin{itemize}
\tightlist
\item
  Sam Smith and \href{http://foo.bar/baz}{Jim Jones}, \emph{Advantages
  of static websites}.
\item
  Jim Jones, \emph{ὕαλον ϕαγεῖν δύναμαι}.
\item
  \emph{Seminar on web security}.
\end{itemize}

\end{document}⏎ 
```

**Comment by DrEntropy** [comment]
I have not looked at this for... years.  I am not in a position to test this out again on a current version, so  I am closing this issue as being 'overcome by events' .
