### ISSUE TITLE
yst.cabal is out of date, as it's no longer possible to install via "cabal install yst".

### ISSUE THREAD

**Issue by AleksandarMicovic** [jgm/yst#39]
Unfortunately, I don't know much about Haskell to help with this, but I figured it'd be good idea to give a heads up.

```
$ cabal install yst
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: yst-0.4.1.1 (user goal)
trying: HDBC-sqlite3-2.3.3.0 (dependency of yst-0.4.1.1)
trying: mtl-2.1.3.1/installed-96f... (dependency of HDBC-sqlite3-2.3.3.0)
trying: pandoc-1.13.2 (dependency of yst-0.4.1.1)
trying: temporary-1.2.0.3 (dependency of pandoc-1.13.2)
trying: exceptions-0.8 (dependency of temporary-1.2.0.3)
trying: transformers-compat-0.4.0.4 (dependency of exceptions-0.8)
trying: transformers-compat-0.4.0.4:-two
rejecting: transformers-compat-0.4.0.4:-three (conflict: mtl =>
transformers==0.3.0.0/installed-645..., transformers-compat-0.4.0.4:three =>
transformers>=0.4.1 && <0.5)
rejecting: transformers-compat-0.4.0.4:+three (manual flag can only be changed
explicitly)
Backjump limit reached (change with --max-backjumps).
```

**Comment by jgm** [comment]
You could try installing in a sandbox (assuming a relatively
recent cabal):

    cabal sandbox init
    cabal install

Alternatively, if you don't have lots of other Haskell stuff
you use, you could remove the `~/.ghc` directory and try
again.

I don't see any evident problems with yst.cabal.

+++ Aleksandar Mićović [Feb 18 15 14:17 ]:

**Comment by AleksandarMicovic** [comment]
Hey, thanks for the answer! So, none of that works out of the box, and neither does setting the max backjumps to something ridiculously high like 10,000. However, running,

```bash
$ cabal install yst --max-backjumps=-1 --reorder-goals
```

managed to find a dependency solution after running for nearly 4 hours on my machine.

I'll go ahead and close this ticket now, as it's inaccurate. Thanks for suggestions.

**Comment by jgm** [comment]
I didn't have any problems installing here, probably because
I have older versions of some packages installed.  If you don't
mind posting the output of `ghc-pkg list`, that might help
debug if similar issues come up for others.

+++ Aleksandar Mićović [Feb 19 15 06:48 ]:

**Comment by AleksandarMicovic** [comment]
Sure thing. For future reference for anyone stumbling upon this same problem:

```bash
$ ghc-pkg list
/usr/local/Cellar/ghc/7.8.4/lib/ghc-7.8.4/package.conf.d
   Cabal-1.18.1.5
   array-0.5.0.0
   base-4.7.0.2
   bin-package-db-0.0.0.0
   binary-0.7.1.0
   bytestring-0.10.4.0
   containers-0.5.5.1
   deepseq-1.3.0.2
   directory-1.2.1.0
   filepath-1.3.0.2
   ghc-7.8.4
   ghc-prim-0.3.1.0
   haskeline-0.7.1.2
   haskell2010-1.1.2.0
   haskell98-2.0.0.3
   hoopl-3.10.0.1
   hpc-0.6.0.1
   integer-gmp-0.5.1.0
   old-locale-1.0.0.6
   old-time-1.1.0.2
   pretty-1.1.1.1
   process-1.2.0.0
   rts-1.0
   template-haskell-2.9.0.0
   terminfo-0.4.0.0
   time-1.4.2
   transformers-0.3.0.0
   unix-2.7.0.1
   xhtml-3000.2.1
```
